export const TRENDING_SUCCESS = "TRENDING_SUCCESS";
export const TRENDING_FAIL = "TRENDING_FAIL";
export const TRENDING_REQUEST = "TRENDING_REQUEST";

export const ORIGINAL_SUCCESS = "ORIGINAL_SUCCESS";
export const ORIGINAL_FAIL = "ORIGINAL_FAIL";
export const ORIGINAL_REQUEST = "ORIGINAL_REQUEST";

export const TOP_RATED_SUCCESS = "TOP_RATED_SUCCESS";
export const TOP_RATED_FAIL = "TOP_RATED_FAIL";
export const TOP_RATED_REQUEST = "TOP_RATED_REQUEST";

export const ACTION_MOVIES_SUCCESS = "ACTION_MOVIES_SUCCESS";
export const ACTION_MOVIES_FAIL = "ACTION_MOVIES_FAIL";
export const ACTION_MOVIES_REQUEST = "ACTION_MOVIES_REQUEST";

export const DOCUMENTARY_SUCCESS = "DOCUMENTARY_SUCCESS";
export const DOCUMENTARY_FAIL = "DOCUMENTARY_FAIL";
export const DOCUMENTARY_REQUEST = "DOCUMENTARY_REQUEST";

export const COMEDY_SUCCESS = "COMEDY_SUCCESS";
export const COMEDY_FAIL = "COMEDY_FAIL";
export const COMEDY_REQUEST = "COMEDY_REQUEST";

export const HORROR_SUCCESS = "HORROR_SUCCESS";
export const HORROR_FAIL = "HORROR_FAIL";
export const HORROR_REQUEST = "HORROR_REQUEST";

export const ROMANCE_SUCCESS = "ROMANCE_SUCCESS";
export const ROMANCE_FAIL = "ROMANCE_FAIL";
export const ROMANCE_REQUEST = "ROMANCE_REQUEST";


export const TRENDING_TV_SUCCESS = "TRENDING_TV_SUCCESS";
export const TRENDING_TV_FAIL = "TRENDING_TV_FAIL";
export const TRENDING_TV_REQUEST = "TRENDING_TV_REQUEST";

export const ORIGINAL_TV_SUCCESS = "ORIGINAL_TV_SUCCESS";
export const ORIGINAL_TV_FAIL = "ORIGINAL_TV_FAIL";
export const ORIGINAL_TV_REQUEST = "ORIGINAL_TV_REQUEST";

export const TOP_RATED_TV_SUCCESS = "TOP_RATED_TV_SUCCESS";
export const TOP_RATED_TV_FAIL = "TOP_RATED_TV_FAIL";
export const TOP_RATED_TV_REQUEST = "TOP_RATED_TV_REQUEST";

export const ACTION_TV_SUCCESS = "ACTION_TV_SUCCESS";
export const ACTION_TV_FAIL = "ACTION_TV_FAIL";
export const ACTION_TV_REQUEST = "ACTION_TV_REQUEST";

export const DOCUMENTARY_TV_SUCCESS = "DOCUMENTARY_TV_SUCCESS";
export const DOCUMENTARY_TV_FAIL = "DOCUMENTARY_TV_FAIL";
export const DOCUMENTARY_TV_REQUEST = "DOCUMENTARY_TV_REQUEST";

export const COMEDY_TV_SUCCESS = "COMEDY_TV_SUCCESS";
export const COMEDY_TV_FAIL = "COMEDY_TV_FAIL";
export const COMEDY_TV_REQUEST = "COMEDY_TV_REQUEST";

export const HORROR_TV_SUCCESS = "HORROR_TV_SUCCESS";
export const HORROR_TV_FAIL = "HORROR_TV_FAIL";
export const HORROR_TV_REQUEST = "HORROR_TV_REQUEST";

export const ROMANCE_TV_SUCCESS = "ROMANCE_TV_SUCCESS";
export const ROMANCE_TV_FAIL = "ROMANCE_TV_FAIL";
export const ROMANCE_TV_REQUEST = "ROMANCE_TV_REQUEST";